[project]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["nvidia/label/cuda-12.4.0", "nvidia", "pytorch", "conda-forge"]
description = "Add a short description here"
name = "ATM"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
train = "python -m train_libero_policy_atm --suite libero_goal --track-transformer results/track_transformer/libero_track_transformer_libero-goal/"
[dependencies]
cuda = "12.4.*"
pytorch-cuda = "12.4.*"
cuda-driver-dev = "12.4.*"
pytorch = "*"
torchaudio = "*"
torchvision = "*"
libjpeg-turbo = { channel = "conda-forge" }
opencv="*"
# python = "3.10.*"
hydra-core = "*"
lightning = "*"
einops = "*"
natsort = "*"
h5py = "*"
robomimic = "*"
